// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:large-record

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
	"unsafe"
	"wit_component/export_test_large_record_status_handler"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, 32, 8))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport test:large-record/status-handler#get-status
func wasm_export_test_large_record_status_handler_get_status() uintptr {

	result := export_test_large_record_status_handler.GetStatus()
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = ((result).Coords).X
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = ((result).Coords).Y
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((result).Coords).Z
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int32((result).Health)
	var result0 int32
	if (result).Alive {
		result0 = 1
	} else {
		result0 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int8(result0)
	*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = int64((result).Score)
	return exportReturnArea

}

//go:wasmexport test:large-record/status-handler#get-position
func wasm_export_test_large_record_status_handler_get_position() uintptr {

	result := export_test_large_record_status_handler.GetPosition()
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = (result).X
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = (result).Y
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = (result).Z
	return exportReturnArea

}

// Unused, but present to make the compiler happy
func main() {}
