// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:large-record

package test_large_record_host_data

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
	"unsafe"
	"wit_component/test_large_record_types"
)

type Coordinates = test_large_record_types.Coordinates

//go:wasmimport test:large-record/host-data get-position
func wasm_import_get_position(arg0 uintptr)

func GetPosition() test_large_record_types.Coordinates {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, 12, 4))
	wasm_import_get_position(returnArea)
	result := test_large_record_types.Coordinates{*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0)), *(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4)), *(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))}
	return result

}
