// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:variantlog

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
	"unsafe"
	"wit_component/export_test_variantlog_processor"
	"wit_component/test_variantlog_types"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, 8, 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport test:variantlog/processor#process-entry
func wasm_export_test_variantlog_processor_process_entry(arg0 int32, arg1 uintptr, arg2 uint32) uintptr {

	var variant test_variantlog_types.LogEntry
	switch arg0 {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(arg1)), arg2)

		variant = test_variantlog_types.MakeLogEntryMessage(value)

	case 1:

		variant = test_variantlog_types.MakeLogEntryCode(uint32(int32(arg1)))

	case 2:

		variant = test_variantlog_types.MakeLogEntryLevel(uint8(int32(arg1)))

	default:
		panic("unreachable")
	}
	wit_runtime.Unpin()
	result := export_test_variantlog_processor.ProcessEntry(variant)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int32((result).Count)
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32((result).LastSeverity))
	return exportReturnArea

}

// Unused, but present to make the compiler happy
func main() {}
