// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:variantlog

package test_variantlog_types

import ()

const (
	SeverityInfo    uint8 = 0
	SeverityWarning uint8 = 1
	SeverityError   uint8 = 2
)

type Severity = uint8

const (
	LogEntryMessage uint8 = 0
	LogEntryCode    uint8 = 1
	LogEntryLevel   uint8 = 2
)

type LogEntry struct {
	tag   uint8
	value any
}

func (self LogEntry) Tag() uint8 {
	return self.tag
}

func (self LogEntry) Message() string {
	if self.tag != LogEntryMessage {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self LogEntry) Code() uint32 {
	if self.tag != LogEntryCode {
		panic("tag mismatch")
	}
	return self.value.(uint32)
}
func (self LogEntry) Level() Severity {
	if self.tag != LogEntryLevel {
		panic("tag mismatch")
	}
	return self.value.(Severity)
}

func MakeLogEntryMessage(value string) LogEntry {
	return LogEntry{LogEntryMessage, value}
}
func MakeLogEntryCode(value uint32) LogEntry {
	return LogEntry{LogEntryCode, value}
}
func MakeLogEntryLevel(value Severity) LogEntry {
	return LogEntry{LogEntryLevel, value}
}

type LogResult struct {
	Count        uint32
	LastSeverity Severity
}
