// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:repro

package test_repro_host_ops

import (
	"wit_component/test_repro_types"
)

type ProcessResult = test_repro_types.ProcessResult

//go:wasmimport test:repro/host-ops get-value
func wasm_import_get_value() int32

func GetValue() uint32 {

	result := wasm_import_get_value()
	return uint32(result)

}

//go:wasmimport test:repro/host-ops get-random-len
func wasm_import_get_random_len(arg0 int64) int64

func GetRandomLen(len uint64) uint64 {

	result := wasm_import_get_random_len(int64(len))
	return uint64(result)

}
