// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:repro

package test_repro_host_ops

import ()

//go:wasmimport test:repro/host-ops get-value
func wasm_import_get_value() int32

func GetValue() uint32 {

	result := wasm_import_get_value()
	return uint32(result)

}
