// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:repro

package test_repro_types

import (
	"github.com/bytecodealliance/wit-bindgen/wit_types"
)

// A result record returned from handler exports.
type ProcessResult struct {
	Value uint32
	Ok    bool
}

const (
	ColorRed   uint8 = 0
	ColorGreen uint8 = 1
	ColorBlue  uint8 = 2
)

// Color enum for echo-enum test.
type Color = uint8

const (
	PermissionsRead    uint8 = 1 << 0
	PermissionsWrite   uint8 = 1 << 1
	PermissionsExecute uint8 = 1 << 2
)

// Permissions flags for echo-flags test.
type Permissions = uint8

const (
	ShapeCircle uint8 = 0
	ShapeSquare uint8 = 1
	ShapeNone   uint8 = 2
)

// Shape variant for echo-variant test.
type Shape struct {
	tag   uint8
	value any
}

func (self Shape) Tag() uint8 {
	return self.tag
}

func (self Shape) Circle() float64 {
	if self.tag != ShapeCircle {
		panic("tag mismatch")
	}
	return self.value.(float64)
}
func (self Shape) Square() float64 {
	if self.tag != ShapeSquare {
		panic("tag mismatch")
	}
	return self.value.(float64)
}

func MakeShapeCircle(value float64) Shape {
	return Shape{ShapeCircle, value}
}
func MakeShapeSquare(value float64) Shape {
	return Shape{ShapeSquare, value}
}
func MakeShapeNone() Shape {
	return Shape{ShapeNone, nil}
}

// A record with an option field, mirroring director's session-event.
type EventData struct {
	EventType Color
	Metadata  wit_types.Option[[]uint8]
}

// A record containing a variant field.
type TaggedShape struct {
	Tag   string
	Shape Shape
}

// Deeply nested record: innermost layer.
type NestedInner struct {
	Label  string
	Score  float64
	Active bool
}

// Deeply nested record: middle layer with inner record, list, option, variant.
type NestedMiddle struct {
	Inner    NestedInner
	Tags     []string
	Priority wit_types.Option[uint32]
	Shape    Shape
}

// Deeply nested record: outermost input with all composite types nested.
type ComplexInput struct {
	Id       string
	Middle   NestedMiddle
	Color    Color
	Metadata wit_types.Option[[]uint8]
}

// Deeply nested record: detail inside output.
type ResultDetail struct {
	Code    uint32
	Message string
	Extra   wit_types.Option[string]
}

// Deeply nested record: complex output with nested record, list, option, variant, enum.
type ComplexOutput struct {
	Success bool
	Detail  ResultDetail
	Values  []uint32
	Event   EventData
	Label   wit_types.Option[string]
}
