// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:repro

package test_repro_types

import ()

// A result record returned from handler exports.
type ProcessResult struct {
	Value uint32
	Ok    bool
}
