// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     docs:calculator

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
	"unsafe"
	"wit_component/export_wit_world"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, (2 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport get-plugin-name
func wasm_export_wit_world_get_plugin_name() uintptr {

	pinner := &syncExportPinner
	result := export_wit_world.GetPluginName()
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_get-plugin-name
func wasm_export_post_return_wit_world_get_plugin_name(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport evaluate
func wasm_export_wit_world_evaluate(arg0 int32, arg1 int32) int32 {

	result := export_wit_world.Evaluate(arg0, arg1)
	return result

}

// Unused, but present to make the compiler happy
func main() {}
