// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:variantlog

package test_variantlog_processor

import (
	"wit_component/test_variantlog_types"
)

type LogEntry = test_variantlog_types.LogEntry
type LogResult = test_variantlog_types.LogResult
type Severity = test_variantlog_types.Severity
