// internal/component/testdata/testdata.go

package testdata

import (
	_ "embed"
)

// EmptyComponent is a minimal valid component with no content.
// Binary: magic(4) + version(2) + layer(2) = 8 bytes
//
//go:embed empty.wasm
var EmptyComponent []byte

// AddS32Component exports an add function: (s32, s32) -> s32
// Generated by: go run gen/gen_add_s32.go
//
//go:embed add_s32.wasm
var AddS32Component []byte

// EchoRecordComponent exports an echo function: (point) -> point
// where point is a record { x: s32, y: s32 }
// Generated by: go run gen/gen_echo_record.go
//
//go:embed echo_record.wasm
var EchoRecordComponent []byte
