// internal/component/testdata/testdata.go

package testdata

import (
	_ "embed"
)

// EmptyComponent is a minimal valid component with no content.
// Binary: magic(4) + version(2) + layer(2) = 8 bytes
//
//go:embed empty.wasm
var EmptyComponent []byte

// AddS32Component exports an add function: (s32, s32) -> s32
// Generated by: go run gen/gen_add_s32.go
//
//go:embed add_s32.wasm
var AddS32Component []byte

// EchoRecordComponent exports an echo function: (point) -> point
// where point is a record { x: s32, y: s32 }
// Generated by: go run gen/gen_echo_record.go
//
//go:embed echo_record.wasm
var EchoRecordComponent []byte

// OptionRoundtripComponent exports an echo function: (option<s32>) -> option<s32>
// that returns the input unchanged.
// Generated by: go run gen/gen_option_roundtrip.go
//
//go:embed option_roundtrip.wasm
var OptionRoundtripComponent []byte

// ListSumComponent exports a sum function: (list<s32>) -> s32
// that sums all elements in the list.
// Generated by: go run gen/gen_list_sum.go
//
//go:embed list_sum.wasm
var ListSumComponent []byte
