// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:nested-types

package test_nested_types_types

import ()

type Item struct {
	Id   uint32
	Name string
}
