// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:nested-types

package test_nested_types_handler

import (
	"wit_component/test_nested_types_types"
)

type Item = test_nested_types_types.Item
