// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:nested-types

package test_nested_types_store

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"runtime"
	"unsafe"
	"wit_component/test_nested_types_types"
)

type Item = test_nested_types_types.Item

//go:wasmimport test:nested-types/store get-item
func wasm_import_get_item(arg0 int32, arg1 uintptr)

func GetItem(id uint32) wit_types.Option[test_nested_types_types.Item] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	wasm_import_get_item(int32(id), returnArea)
	var option wit_types.Option[test_nested_types_types.Item]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = wit_types.None[test_nested_types_types.Item]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

		option = wit_types.Some[test_nested_types_types.Item](test_nested_types_types.Item{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))), value})
	default:
		panic("unreachable")
	}
	result := option
	return result

}
