// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:variantlog

package test_variantlog_host_logger

import (
	"wit_component/test_variantlog_types"
)

type Severity = test_variantlog_types.Severity

//go:wasmimport test:variantlog/host-logger get-default-severity
func wasm_import_get_default_severity() int32

func GetDefaultSeverity() test_variantlog_types.Severity {

	result := wasm_import_get_default_severity()
	return uint8(result)

}
