// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:large-record

package test_large_record_types

import ()

type Coordinates struct {
	X int32
	Y int32
	Z int32
}

type FullStatus struct {
	Coords Coordinates
	Health uint32
	Alive  bool
	Score  uint64
}
