// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:repro

package test_repro_handler

import (
	"wit_component/test_repro_types"
)

type ProcessResult = test_repro_types.ProcessResult
type Color = test_repro_types.Color
type Permissions = test_repro_types.Permissions
type Shape = test_repro_types.Shape
type EventData = test_repro_types.EventData
type TaggedShape = test_repro_types.TaggedShape
type ComplexInput = test_repro_types.ComplexInput
type ComplexOutput = test_repro_types.ComplexOutput
type NestedInner = test_repro_types.NestedInner
type NestedMiddle = test_repro_types.NestedMiddle
type ResultDetail = test_repro_types.ResultDetail
