// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:repro

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
	"unsafe"
	"wit_component/export_test_repro_handler"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, 8, 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport test:repro/handler#process
func wasm_export_test_repro_handler_process() uintptr {

	result := export_test_repro_handler.Process()
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int32((result).Value)
	var result0 int32
	if (result).Ok {
		result0 = 1
	} else {
		result0 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(result0)
	return exportReturnArea

}

// Unused, but present to make the compiler happy
func main() {}
