// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:repro

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"runtime"
	"unsafe"
	"wit_component/export_test_repro_handler"
	"wit_component/test_repro_types"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, (16 * 4), 8))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport test:repro/handler#process
func wasm_export_test_repro_handler_process() uintptr {

	result := export_test_repro_handler.Process()
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int32((result).Value)
	var result0 int32
	if (result).Ok {
		result0 = 1
	} else {
		result0 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(result0)
	return exportReturnArea

}

//go:wasmexport test:repro/handler#process-random
func wasm_export_test_repro_handler_process_random(arg0 int64) int64 {

	result := export_test_repro_handler.ProcessRandom(uint64(arg0))
	return int64(result)

}

//go:wasmexport test:repro/handler#process-random-bytes
func wasm_export_test_repro_handler_process_random_bytes(arg0 int32) uintptr {

	pinner := &syncExportPinner
	result := export_test_repro_handler.ProcessRandomBytes(uint32(arg0))
	data := unsafe.Pointer(unsafe.SliceData(result))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(data)))
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#process-random-bytes
func wasm_export_post_return_test_repro_handler_process_random_bytes(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:repro/handler#echo-string
func wasm_export_test_repro_handler_echo_string(arg0 uintptr, arg1 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	wit_runtime.Unpin()
	result := export_test_repro_handler.EchoString(value)
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#echo-string
func wasm_export_post_return_test_repro_handler_echo_string(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:repro/handler#call-send-enum
func wasm_export_test_repro_handler_call_send_enum(arg0 int32, arg1 uintptr, arg2 uint32) int32 {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg1)), arg2)
	wit_runtime.Unpin()
	result := export_test_repro_handler.CallSendEnum(uint8(arg0), value)
	return int32(result)

}

//go:wasmexport test:repro/handler#call-send-event
func wasm_export_test_repro_handler_call_send_event(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32) int32 {

	var option wit_types.Option[[]uint8]
	switch arg1 {
	case 0:

		option = wit_types.None[[]uint8]()
	case 1:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(arg2)), arg3)

		option = wit_types.Some[[]uint8](value)
	default:
		panic("unreachable")
	}
	wit_runtime.Unpin()
	result := export_test_repro_handler.CallSendEvent(test_repro_types.EventData{uint8(arg0), option})
	return int32(result)

}

//go:wasmexport test:repro/handler#echo-bool
func wasm_export_test_repro_handler_echo_bool(arg0 int32) int32 {

	result := export_test_repro_handler.EchoBool((arg0 != 0))
	var result0 int32
	if result {
		result0 = 1
	} else {
		result0 = 0
	}
	return result0

}

//go:wasmexport test:repro/handler#echo-s8
func wasm_export_test_repro_handler_echo_s8(arg0 int32) int32 {

	result := export_test_repro_handler.EchoS8(int8(arg0))
	return int32(result)

}

//go:wasmexport test:repro/handler#echo-u8
func wasm_export_test_repro_handler_echo_u8(arg0 int32) int32 {

	result := export_test_repro_handler.EchoU8(uint8(arg0))
	return int32(result)

}

//go:wasmexport test:repro/handler#echo-s16
func wasm_export_test_repro_handler_echo_s16(arg0 int32) int32 {

	result := export_test_repro_handler.EchoS16(int16(arg0))
	return int32(result)

}

//go:wasmexport test:repro/handler#echo-u16
func wasm_export_test_repro_handler_echo_u16(arg0 int32) int32 {

	result := export_test_repro_handler.EchoU16(uint16(arg0))
	return int32(result)

}

//go:wasmexport test:repro/handler#echo-f32
func wasm_export_test_repro_handler_echo_f32(arg0 float32) float32 {

	result := export_test_repro_handler.EchoF32(arg0)
	return result

}

//go:wasmexport test:repro/handler#echo-f64
func wasm_export_test_repro_handler_echo_f64(arg0 float64) float64 {

	result := export_test_repro_handler.EchoF64(arg0)
	return result

}

//go:wasmexport test:repro/handler#echo-char
func wasm_export_test_repro_handler_echo_char(arg0 int32) int32 {

	result := export_test_repro_handler.EchoChar(rune(arg0))
	return int32(result)

}

//go:wasmexport test:repro/handler#echo-enum
func wasm_export_test_repro_handler_echo_enum(arg0 int32) int32 {

	result := export_test_repro_handler.EchoEnum(uint8(arg0))
	return int32(result)

}

//go:wasmexport test:repro/handler#echo-flags
func wasm_export_test_repro_handler_echo_flags(arg0 int32) int32 {

	result := export_test_repro_handler.EchoFlags(uint8(arg0))
	return int32(result)

}

//go:wasmexport test:repro/handler#echo-variant
func wasm_export_test_repro_handler_echo_variant(arg0 int32, arg1 float64) uintptr {

	var variant test_repro_types.Shape
	switch arg0 {
	case 0:

		variant = test_repro_types.MakeShapeCircle(arg1)

	case 1:

		variant = test_repro_types.MakeShapeSquare(arg1)

	case 2:

		variant = test_repro_types.MakeShapeNone()

	default:
		panic("unreachable")
	}
	result := export_test_repro_handler.EchoVariant(variant)

	switch result.Tag() {
	case test_repro_types.ShapeCircle:
		payload := result.Circle()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = payload

	case test_repro_types.ShapeSquare:
		payload := result.Square()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = payload

	case test_repro_types.ShapeNone:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(2))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport test:repro/handler#make-ok
func wasm_export_test_repro_handler_make_ok(arg0 int32) uintptr {

	pinner := &syncExportPinner
	result := export_test_repro_handler.MakeOk(uint32(arg0))

	switch result.Tag() {
	case wit_types.ResultOk:
		payload := result.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int32(payload)

	case wit_types.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#make-ok
func wasm_export_post_return_test_repro_handler_make_ok(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:repro/handler#make-err
func wasm_export_test_repro_handler_make_err(arg0 uintptr, arg1 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	wit_runtime.Unpin()
	result := export_test_repro_handler.MakeErr(value)

	switch result.Tag() {
	case wit_types.ResultOk:
		payload := result.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int32(payload)

	case wit_types.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#make-err
func wasm_export_post_return_test_repro_handler_make_err(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:repro/handler#add-three
func wasm_export_test_repro_handler_add_three(arg0 int32, arg1 int32, arg2 int32) int32 {

	result := export_test_repro_handler.AddThree(uint32(arg0), uint32(arg1), uint32(arg2))
	return int32(result)

}

//go:wasmexport test:repro/handler#concat-strings
func wasm_export_test_repro_handler_concat_strings(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	value0 := unsafe.String((*uint8)(unsafe.Pointer(arg2)), arg3)
	wit_runtime.Unpin()
	result := export_test_repro_handler.ConcatStrings(value, value0)
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#concat-strings
func wasm_export_post_return_test_repro_handler_concat_strings(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:repro/handler#mixed-params
func wasm_export_test_repro_handler_mixed_params(arg0 uintptr, arg1 uint32, arg2 int32, arg3 int32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	wit_runtime.Unpin()
	result := export_test_repro_handler.MixedParams(value, uint32(arg2), (arg3 != 0))
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#mixed-params
func wasm_export_post_return_test_repro_handler_mixed_params(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:repro/handler#call-get-color
func wasm_export_test_repro_handler_call_get_color() int32 {

	result := export_test_repro_handler.CallGetColor()
	return int32(result)

}

//go:wasmexport test:repro/handler#call-check-option
func wasm_export_test_repro_handler_call_check_option(arg0 int32, arg1 int32) int32 {

	var option wit_types.Option[uint32]
	switch arg0 {
	case 0:

		option = wit_types.None[uint32]()
	case 1:

		option = wit_types.Some[uint32](uint32(arg1))
	default:
		panic("unreachable")
	}
	result := export_test_repro_handler.CallCheckOption(option)
	return int32(result)

}

//go:wasmexport test:repro/handler#call-get-event
func wasm_export_test_repro_handler_call_get_event() uintptr {

	pinner := &syncExportPinner
	result := export_test_repro_handler.CallGetEvent()
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32((result).EventType))

	switch (result).Metadata.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (result).Metadata.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(1))
		data := unsafe.Pointer(unsafe.SliceData(payload))
		pinner.Pin(data)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(data)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#call-get-event
func wasm_export_post_return_test_repro_handler_call_get_event(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:repro/handler#call-check-opt-bytes
func wasm_export_test_repro_handler_call_check_opt_bytes(arg0 int32, arg1 uintptr, arg2 uint32) int32 {

	var option wit_types.Option[[]uint8]
	switch arg0 {
	case 0:

		option = wit_types.None[[]uint8]()
	case 1:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(arg1)), arg2)

		option = wit_types.Some[[]uint8](value)
	default:
		panic("unreachable")
	}
	wit_runtime.Unpin()
	result := export_test_repro_handler.CallCheckOptBytes(option)
	return int32(result)

}

//go:wasmexport test:repro/handler#call-send-tagged-shape
func wasm_export_test_repro_handler_call_send_tagged_shape(arg0 uintptr, arg1 uint32, arg2 int32, arg3 float64) int32 {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	var variant test_repro_types.Shape
	switch arg2 {
	case 0:

		variant = test_repro_types.MakeShapeCircle(arg3)

	case 1:

		variant = test_repro_types.MakeShapeSquare(arg3)

	case 2:

		variant = test_repro_types.MakeShapeNone()

	default:
		panic("unreachable")
	}
	wit_runtime.Unpin()
	result := export_test_repro_handler.CallSendTaggedShape(test_repro_types.TaggedShape{value, variant})
	return int32(result)

}

//go:wasmexport test:repro/handler#call-send-events
func wasm_export_test_repro_handler_call_send_events(arg0 uintptr, arg1 uint32) int32 {

	result := make([]test_repro_types.EventData, 0, arg1)
	for index := 0; index < int(arg1); index++ {
		base := unsafe.Add(unsafe.Pointer(arg0), index*(4*4))
		var option wit_types.Option[[]uint8]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))) {
		case 0:

			option = wit_types.None[[]uint8]()
		case 1:
			value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			option = wit_types.Some[[]uint8](value)
		default:
			panic("unreachable")
		}

		result = append(result, test_repro_types.EventData{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)))), option})
	}

	wit_runtime.Unpin()
	result0 := export_test_repro_handler.CallSendEvents(result)
	return int32(result0)

}

//go:wasmexport test:repro/handler#process-with-tag
func wasm_export_test_repro_handler_process_with_tag(arg0 uintptr, arg1 uint32) uintptr {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	wit_runtime.Unpin()
	result := export_test_repro_handler.ProcessWithTag(value)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int32((result).Value)
	var result0 int32
	if (result).Ok {
		result0 = 1
	} else {
		result0 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(result0)
	return exportReturnArea

}

//go:wasmexport test:repro/handler#process-two-strings
func wasm_export_test_repro_handler_process_two_strings(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) uintptr {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	value0 := unsafe.String((*uint8)(unsafe.Pointer(arg2)), arg3)
	wit_runtime.Unpin()
	result := export_test_repro_handler.ProcessTwoStrings(value, value0)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int32((result).Value)
	var result1 int32
	if (result).Ok {
		result1 = 1
	} else {
		result1 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(result1)
	return exportReturnArea

}

//go:wasmexport test:repro/handler#count-bytes
func wasm_export_test_repro_handler_count_bytes(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) int32 {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	value0 := unsafe.Slice((*uint8)(unsafe.Pointer(arg2)), arg3)
	wit_runtime.Unpin()
	result := export_test_repro_handler.CountBytes(value, value0)
	return int32(result)

}

//go:wasmexport test:repro/handler#handle-bytes
func wasm_export_test_repro_handler_handle_bytes(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) uintptr {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	value0 := unsafe.Slice((*uint8)(unsafe.Pointer(arg2)), arg3)
	wit_runtime.Unpin()
	result := export_test_repro_handler.HandleBytes(value, value0)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int32((result).Value)
	var result1 int32
	if (result).Ok {
		result1 = 1
	} else {
		result1 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(result1)
	return exportReturnArea

}

//go:wasmexport test:repro/handler#handle-event
func wasm_export_test_repro_handler_handle_event(arg0 uintptr, arg1 uint32, arg2 int32, arg3 int32, arg4 uintptr, arg5 uint32) uintptr {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	var option wit_types.Option[[]uint8]
	switch arg3 {
	case 0:

		option = wit_types.None[[]uint8]()
	case 1:
		value0 := unsafe.Slice((*uint8)(unsafe.Pointer(arg4)), arg5)

		option = wit_types.Some[[]uint8](value0)
	default:
		panic("unreachable")
	}
	wit_runtime.Unpin()
	result := export_test_repro_handler.HandleEvent(value, test_repro_types.EventData{uint8(arg2), option})
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int32((result).Value)
	var result1 int32
	if (result).Ok {
		result1 = 1
	} else {
		result1 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(result1)
	return exportReturnArea

}

//go:wasmexport test:repro/handler#process-complex
func wasm_export_test_repro_handler_process_complex(arg0 uintptr) int32 {

	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 4)))
	value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (8 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (8 + 3*4))))
	value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (8 + 4*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (8 + 5*4))))
	result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 7*4))))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 7*4)))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 6*4))))), index*(2*4))
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

		result = append(result, value2)
	}

	var option wit_types.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 8*4)))) {
	case 0:

		option = wit_types.None[uint32]()
	case 1:

		option = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (28 + 8*4)))))
	default:
		panic("unreachable")
	}
	var variant test_repro_types.Shape
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (32 + 8*4)))) {
	case 0:

		variant = test_repro_types.MakeShapeCircle(*(*float64)(unsafe.Add(unsafe.Pointer(arg0), (40 + 8*4))))

	case 1:

		variant = test_repro_types.MakeShapeSquare(*(*float64)(unsafe.Add(unsafe.Pointer(arg0), (40 + 8*4))))

	case 2:

		variant = test_repro_types.MakeShapeNone()

	default:
		panic("unreachable")
	}
	var option4 wit_types.Option[[]uint8]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (48 + 9*4)))) {
	case 0:

		option4 = wit_types.None[[]uint8]()
	case 1:
		value3 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (48 + 10*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (48 + 11*4))))

		option4 = wit_types.Some[[]uint8](value3)
	default:
		panic("unreachable")
	}
	wit_runtime.Unpin()
	result5 := export_test_repro_handler.ProcessComplex(value, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (2 * 4)))), test_repro_types.ComplexInput{value0, test_repro_types.NestedMiddle{test_repro_types.NestedInner{value1, *(*float64)(unsafe.Add(unsafe.Pointer(arg0), (8 + 6*4))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 6*4)))) != 0)}, result, option, variant}, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (48 + 8*4))))), option4})
	return int32(result5)

}

//go:wasmexport test:repro/handler#transform-complex
func wasm_export_test_repro_handler_transform_complex(arg0 uintptr, arg1 uint32, arg2 int32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	wit_runtime.Unpin()
	result := export_test_repro_handler.TransformComplex(value, uint32(arg2))
	var result0 int32
	if (result).Success {
		result0 = 1
	} else {
		result0 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(result0)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int32(((result).Detail).Code)
	utf8 := unsafe.Pointer(unsafe.StringData(((result).Detail).Message))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len(((result).Detail).Message)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf8)))

	switch ((result).Detail).Extra.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := ((result).Detail).Extra.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = int8(int32(1))
		utf81 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf81)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (6 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = uint32(uintptr(uintptr(utf81)))

	default:
		panic("unreachable")
	}
	data := unsafe.Pointer(unsafe.SliceData((result).Values))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 * 4))) = uint32(uint32(len((result).Values)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (7 * 4))) = uint32(uintptr(uintptr(data)))
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 * 4))) = int8(int32(((result).Event).EventType))

	switch ((result).Event).Metadata.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 * 4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := ((result).Event).Metadata.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 * 4))) = int8(int32(1))
		data2 := unsafe.Pointer(unsafe.SliceData(payload))
		pinner.Pin(data2)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (11 * 4))) = uint32(uintptr(uintptr(data2)))

	default:
		panic("unreachable")
	}

	switch (result).Label.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (13 * 4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (result).Label.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (13 * 4))) = int8(int32(1))
		utf83 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf83)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (15 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (14 * 4))) = uint32(uintptr(uintptr(utf83)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#transform-complex
func wasm_export_post_return_test_repro_handler_transform_complex(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:repro/handler#transform-complex-variant
func wasm_export_test_repro_handler_transform_complex_variant(arg0 uintptr, arg1 uint32, arg2 int32, arg3 float64) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	var variant test_repro_types.Shape
	switch arg2 {
	case 0:

		variant = test_repro_types.MakeShapeCircle(arg3)

	case 1:

		variant = test_repro_types.MakeShapeSquare(arg3)

	case 2:

		variant = test_repro_types.MakeShapeNone()

	default:
		panic("unreachable")
	}
	wit_runtime.Unpin()
	result := export_test_repro_handler.TransformComplexVariant(value, variant)
	var result0 int32
	if (result).Success {
		result0 = 1
	} else {
		result0 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(result0)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int32(((result).Detail).Code)
	utf8 := unsafe.Pointer(unsafe.StringData(((result).Detail).Message))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len(((result).Detail).Message)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf8)))

	switch ((result).Detail).Extra.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := ((result).Detail).Extra.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = int8(int32(1))
		utf81 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf81)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (6 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = uint32(uintptr(uintptr(utf81)))

	default:
		panic("unreachable")
	}
	data := unsafe.Pointer(unsafe.SliceData((result).Values))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 * 4))) = uint32(uint32(len((result).Values)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (7 * 4))) = uint32(uintptr(uintptr(data)))
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 * 4))) = int8(int32(((result).Event).EventType))

	switch ((result).Event).Metadata.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 * 4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := ((result).Event).Metadata.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 * 4))) = int8(int32(1))
		data2 := unsafe.Pointer(unsafe.SliceData(payload))
		pinner.Pin(data2)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (11 * 4))) = uint32(uintptr(uintptr(data2)))

	default:
		panic("unreachable")
	}

	switch (result).Label.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (13 * 4))) = int8(int32(0))

	case wit_types.OptionSome:
		payload := (result).Label.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (13 * 4))) = int8(int32(1))
		utf83 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf83)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (15 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (14 * 4))) = uint32(uintptr(uintptr(utf83)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#transform-complex-variant
func wasm_export_post_return_test_repro_handler_transform_complex_variant(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
