// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:repro

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
	"unsafe"
	"wit_component/export_test_repro_handler"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, (2 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport test:repro/handler#process
func wasm_export_test_repro_handler_process() uintptr {

	result := export_test_repro_handler.Process()
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int32((result).Value)
	var result0 int32
	if (result).Ok {
		result0 = 1
	} else {
		result0 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(result0)
	return exportReturnArea

}

//go:wasmexport test:repro/handler#process-random
func wasm_export_test_repro_handler_process_random(arg0 int64) int64 {

	result := export_test_repro_handler.ProcessRandom(uint64(arg0))
	return int64(result)

}

//go:wasmexport test:repro/handler#process-random-bytes
func wasm_export_test_repro_handler_process_random_bytes(arg0 int32) uintptr {

	pinner := &syncExportPinner
	result := export_test_repro_handler.ProcessRandomBytes(uint32(arg0))
	data := unsafe.Pointer(unsafe.SliceData(result))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(data)))
	return exportReturnArea

}

//go:wasmexport cabi_post_test:repro/handler#process-random-bytes
func wasm_export_post_return_test_repro_handler_process_random_bytes(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
