// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:large-record

package test_large_record_status_handler

import (
	"wit_component/test_large_record_types"
)

type FullStatus = test_large_record_types.FullStatus
type Coordinates = test_large_record_types.Coordinates
