// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.9
//     wasi:clocks@0.2.9
//     wasi:filesystem@0.2.9
//     test:wasi-exercise@0.1.0

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
	"unsafe"
	"wit_component/export_wit_world"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, (2 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport test-fs-set-size
func wasm_export_wit_world_test_fs_set_size() uintptr {

	pinner := &syncExportPinner
	result := export_wit_world.TestFsSetSize()
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_test-fs-set-size
func wasm_export_post_return_wit_world_test_fs_set_size(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test-fs-metadata-hash
func wasm_export_wit_world_test_fs_metadata_hash() uintptr {

	pinner := &syncExportPinner
	result := export_wit_world.TestFsMetadataHash()
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_test-fs-metadata-hash
func wasm_export_post_return_wit_world_test_fs_metadata_hash(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test-fs-is-same-object
func wasm_export_wit_world_test_fs_is_same_object() uintptr {

	pinner := &syncExportPinner
	result := export_wit_world.TestFsIsSameObject()
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_test-fs-is-same-object
func wasm_export_post_return_wit_world_test_fs_is_same_object(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
