// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     test:nested-types

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"runtime"
	"unsafe"
	"wit_component/export_test_nested_types_handler"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, (4 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport test:nested-types/handler#lookup
func wasm_export_test_nested_types_handler_lookup(arg0 int32) uintptr {

	pinner := &syncExportPinner
	result := export_test_nested_types_handler.Lookup(uint32(arg0))

	switch result.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case wit_types.OptionSome:
		payload := result.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int32((payload).Id)
		utf8 := unsafe.Pointer(unsafe.StringData((payload).Name))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len((payload).Name)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_test:nested-types/handler#lookup
func wasm_export_post_return_test_nested_types_handler_lookup(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport test:nested-types/handler#create
func wasm_export_test_nested_types_handler_create(arg0 uintptr, arg1 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	wit_runtime.Unpin()
	result := export_test_nested_types_handler.Create(value)

	switch result.Tag() {
	case wit_types.ResultOk:
		payload := result.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int32((payload).Id)
		utf8 := unsafe.Pointer(unsafe.StringData((payload).Name))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len((payload).Name)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf8)))

	case wit_types.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf80 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf80)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_test:nested-types/handler#create
func wasm_export_post_return_test_nested_types_handler_create(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
