// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
#ifndef __BINDINGS_PLUGIN_H
#define __BINDINGS_PLUGIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct plugin_string_t {
  uint8_t*ptr;
  size_t len;
} plugin_string_t;

// Exported Functions from `plugin`
void exports_plugin_get_plugin_name(plugin_string_t *ret);
int32_t exports_plugin_evaluate(int32_t x, int32_t y);

// Helper Functions

// Sets the string `ret` to reference the input string `s` without copying it
void plugin_string_set(plugin_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void plugin_string_dup(plugin_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void plugin_string_dup_n(plugin_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void plugin_string_free(plugin_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
