// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
#include "plugin.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `plugin`

__attribute__((__weak__, __export_name__("cabi_post_get-plugin-name")))
void __wasm_export_exports_plugin_get_plugin_name_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(2*sizeof(void*))];

// Helper Functions

void plugin_string_set(plugin_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void plugin_string_dup(plugin_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_dup_n(plugin_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_free(plugin_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("get-plugin-name")))
uint8_t * __wasm_export_exports_plugin_get_plugin_name(void) {
  plugin_string_t ret;
  exports_plugin_get_plugin_name(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("evaluate")))
int32_t __wasm_export_exports_plugin_evaluate(int32_t arg, int32_t arg0) {
  int32_t ret = exports_plugin_evaluate(arg, arg0);
  return ret;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_plugin(void);
__attribute__((used))
void __component_type_object_force_link_plugin_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_plugin();
}
